### ISSUE TITLE
Cannot use in presto 0.151

### ISSUE THREAD

**Issue by rgao-aa** [qubole/presto-udfs#18]
My presto's version is 0.151, and after I move the .jar file to /plugin/udfs/ and restart my presto, it kept initializing and didn't work. How can I solve this problem? Is it because my presto's version too new?

**Comment by shubhamtagra** [comment]
Yes, it must be due to that. Presto engine's interfaces changes quite frequently and it is possible that there is a backward incompatible change in newer releases. 

To fix this will require changing code. First step would be to build presto-udfs against presto v0.151 and find out what the incompatibilities are.

**Comment by haitaoyao** [comment]
@stagraqubole There's no getServices() method in Plugin, and no FunctionFactory interface since 0.152, [here's the doc](https://prestodb.io/docs/current/release/release-0.152.html) . How can we deploy the plugin and register the functions?

thanks.

**Comment by shubhamtagra** [comment]
@haitaoyao current implementation is compatible with 0.142 and will require changes for 0.152 compatibility as you have found.

We plan to make this compatible with 0.157 next. Not sure if that will help you with 0.152 but you will have to wait for some time till we are done with 0.157 compatibility. 
Contributions are welcome if you plan to make this compatible with 0.152.

**Comment by haitaoyao** [comment]
@stagraqubole Thanks for your reply. 
Until now, I still didn't find any other way to register the udfs after the function factory interface is removed. You can see the presto engine no longer register the functions other plugin provided [presto code commmit: Remove FunctionFactory](https://github.com/prestodb/presto/commit/a52540185d1394b264a4e749c78d5ba5834e4312)

**Comment by haitaoyao** [comment]
I'm asking the presto developers the same question [here](https://groups.google.com/forum/#!topic/presto-users/fhi1thrAHWw)

**Comment by shubhamtagra** [comment]
It seems its not removed completely, but has been moved around. The Plugins can now return list of functions, see TeradataFunctionsPlugin.java for example in the commit https://github.com/prestodb/presto/pull/5741/files#diff-7f462316886d2546603352d4d4b2721a

I think we can make changes in same way here, i can help out more once we pick up this work.

**Comment by haitaoyao** [comment]
I see. And I also found the official doc: https://prestodb.io/docs/current/develop/functions.html . 
Thanks.
